print(" *** Number Fun !!! ***")
a,b = input("Enter a b : ").split()
print("a=",a,"\ttype =",type(a))
print("b=",b,"\ttype =",type(b))
print("a+b =>",a,"+",b,"=>",a+b)
a = float(a)
b = float(b)
print(f"a/b = {a/b:0.2f}")
print(f"b/a = {b/a:0.3f}")
print(f"a/b = {int(a/b)} r {int(a%b)}")
print(f"b/a = {int(b/a)} r {int(b%a)}")
